-- Add X/Twitter posting fields to calendar_entries
ALTER TABLE calendar_entries
ADD COLUMN IF NOT EXISTS image_urls TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS tweet_id VARCHAR(50) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS tweet_url VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS tweet_ids TEXT DEFAULT NULL;
